server:
  port: 8443
  
spring:
  application:
    name: API-GATEWAY
# Route config
# now we can use api-gateway port nd calling our both service    
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**
        # hystrix config fliter
        filters:
        - name: CircuitBreaker
          args:
            name: USER-SERVICE
            fallbackuri: forward:/userServiceFallBack
        
        # Department service
      - id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE
        predicates:
        - Path=/departments/**
        # hystrix config fliter
        filters:
        - name: CircuitBreaker
          args:
            name: DEPARTMENT-SERVICE
            fallbackuri: forward:/departmentServiceFallBack
        
      
# Hystrix timeout
# THis is for when the service taking time and cant response within 
#     our give time so our fallback method is executed
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMillseconds: 4000

# Actuator Config
# Enable Hystrix Dashboard config
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    
    
