server:
  port: 8445
  
spring:
  application:
    name: CONFIG-SERVER

# Git hub cofig    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gmahor/config-server
          clone-on-start: true  
      
